version: '3'

services:

  mongo:
    image: mongo
    container_name: mongodb-jwt-restful-eample
    networks:
      - jwt-auth-nodeapp-network

  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - jwt-auth-nodeapp-network
    depends_on:
      - mongo

networks:
  jwt-auth-nodeapp-network:
    driver: bridge
